language: python
python:
  - "2.7"
sudo: false
services:
  - elasticsearch
before_script:
  - flake8 mozillians
before_install:
  - git submodule update --init --recursive
  - mysql -e 'create database mozillians character set utf8;'
  - cp mozillians/settings/local.py-travis mozillians/settings/local.py
install:
  - ./peep.sh install -r requirements/default.txt
  - ./peep.sh install -r requirements/default-dev.txt
script:
  - coverage run --source=mozillians manage.py test
after_success:
  - pip install coveralls
  - coveralls

